version: '3'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=websays
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - dev-network


  dev:
    depends_on:
    - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    networks:
      - dev-network
    volumes:
      -  ./data:/app/data


volumes:
  postgres-db:
  data:

networks:
    dev-network:
